### PR TITLE
Feature/cms12 improvements

### PR DESCRIPTION
**Pull request by adnanzameer**
- Implement a feature allowing the tool to be relocated from the admin area, enabling editor access.
- Fixed UI issues for the latest version of the CMS UI.
- Added a column in the table to show block usage count.
- Added support for multiple languages for all block usages across different versions of the owner's content on the references model.
- Sort the list by number of usages.
- Increase page size to 20 to fill up unused space.
- Sort page types and block types in the content type dropdown alphabetically.
- Hide References link if there are no usages of the block.

### CODE REVIEW

**Comment by adnanzameer** [comment]
Optional entry in startup.cs 

  `services.AddContentTypeUsage(o => o.AvailableToEditors = true);`

**Comment by birgitzprinz** [comment]
Thank you Adnan.

**Comment by adnanzameer** [comment]
Is there any chance to get this update out as a Nuget package?

**Comment by birgitzprinz** [comment]
Sure, I'll push this out to our nuget.

**Pull request merged**
